### ISSUE TITLE
关于心金魂银计步器相关内容的汉化

### ISSUE THREAD

**Issue by enler** [Xzonn/PokemonChineseTranslationRevise#2]
Xzonn，你好，儿童节快乐，当然我不是为了说这个才来的，
当年acg汉化组汉化心金魂银的时候，计步器相关的内容都没有汉化，
这其中包括NDS端的计步器菜单以及计步器本体的所有内容，
这都是因为当年没有方法可以让汉化版rom跟计步器进行通信，
但是现在的话可以通过特定的手段让汉化版跟计步器进行通信了，
并且因为可以进行通信的关系，连计步器本体的内容都可以被汉化。

于是我们就研究了相关的问题，并且成功汉化了计步器本体，
但是计步器的汉化需要借助nds端，因此为了发布计步器的汉化，
我们要发布一个心金魂银汉化版rom的补丁，以rom作为载体来帮助汉化计步器（此外我们还另外准备了一个NDS自制软件），
这个补丁包括了计步器本体的汉化，但没有包括nds端菜单部分的汉化。
其实这部分文本我们已经初步翻译完了，由原ACG汉化组的Our Story℃翻译的，
翻译好的文本在这里https://gist.github.com/enler/4aeae23d80e94a94d6d162bcf46487cb
考虑到现在的汉化版本是由你在维护，
我们希望由你完成后续的整合工作，把这份文本导入，
并且整合我们发布的计步器本体汉化补丁，
计步器本体汉化补丁主要是修改了overlay9_0112.bin跟y9.bin这2个文件，只要替换这2个文件就行

**Comment by Xzonn** [comment]
你好，儿童节快乐！
感谢你们对计步器的汉化，之前这部分没有汉化确实是一个遗憾。
文本的导入比较简单，如果需要修改两个文件的话其实也可以做到。
我目前补丁应用工具是拆包然后替换文件，如果有修改的文件可以直接放到补丁包里面，源代码可参见[这里](https://github.com/Xzonn/PokemonChineseTranslationRevise/tree/master/PokemonCTRPatch)。
如果需要我整合的话，可以把这两个文件发给我，我加入到补丁包里面。
再次感谢！

**Comment by enler** [comment]
@Xzonn 需要整合的文件在这里https://github.com/enler/HGSS_PokeWalkerChineseLocalization/tree/master/Release
我们会在今天晚上正式发布计步器的汉化，发布文会附带一份详细的计步器汉化使用教程

**Comment by enler** [comment]
@Xzonn 我们已经发布了，发布地址在这里https://bbs.oldmanemu.net/thread-18167.htm，这个issue我先关闭了，应该没什么问题了

**Comment by Xzonn** [comment]
@enler 谢谢！我今天下午试了一下导入，但是因为我手上没有计步器，没办法进行测试。如果可以的话，想请您先测试一下我导入的补丁是否有效，谢谢！

用法：解压 `Tools.3.1.2.zip`，用 `PokemonCTRPatch.exe` 读取补丁包（`Patch-HG.zip` 或 `Patch-SS.zip`，补丁包不需要解压）和 ROM，然后保存打补丁后的 ROM。

- [Tools.3.1.2.zip](https://github.com/Xzonn/PokemonChineseTranslationRevise/files/8813893/Tools.3.1.2.zip)
- [Patch-HG.zip](https://github.com/Xzonn/PokemonChineseTranslationRevise/files/8813896/Patch-HG.zip)
- [Patch-SS.zip](https://github.com/Xzonn/PokemonChineseTranslationRevise/files/8813897/Patch-SS.zip)

**Comment by enler** [comment]
@Xzonn 初步测了一下心金的没啥问题，但是文本上有些地方要稍微改一下
267的115这句应为“购物区”，
267的49这句应为“将出门中捕捉到的宝可梦\n放进了盒子！[0207]”
267的66这句应为“捕捉到的宝可梦”
这两句原文都是つれてきた，直译不大好翻译
268的31这句应为“[0101,0001]看着这边，\n好像很在意[0108,0004]！”
おでかけで主要都翻译成出门了，有些地方读起来比较生硬，改成外出可能更合适一些

**Comment by Xzonn** [comment]
@enler 感谢反馈，已修改这部分文本：[Patch-HG.zip](https://github.com/Xzonn/PokemonChineseTranslationRevise/files/8823834/Patch-HG.zip)。
另外我可以直接把计步器本体汉化补丁整合进来发布吗？我会在发布页面保留贵组的信息并提供贵组发布地址的链接。

**Comment by Xzonn** [comment]
@enler 好的，谢谢！如果测试没有问题的话我明天就发布新的补丁。

**Comment by enler** [comment]
@Xzonn 另外署名的话，计步器本体汉化写圈叉汉化组的就行，然后贴上链接，计步器菜单内容的翻译名字写OS，不用写明是acg汉化组的，然后我个人的名字就不用出现了

**Comment by Xzonn** [comment]
@enler 好的，了解了，谢谢！

**Comment by Xzonn** [comment]
@enler 已整合并发布 1.5.0 版本补丁，此 issue 暂时关闭。
