### ISSUE TITLE
珍珠钻石的标题封面汉化

### ISSUE THREAD

**Issue by ppllouf** [Xzonn/PokemonChineseTranslationRevise#5]
[汉化更新.zip](https://github.com/Xzonn/PokemonChineseTranslationRevise/files/12215694/default.zip)
我已经做好了新图标的美化
开场白色logo为日文（因为以前写的是“口袋妖怪”）
主界面为标题图标由 [@大神丶橡皮](https://tieba.baidu.com/home/main?un=%E5%A4%A7%E7%A5%9E%E4%B8%B6%E6%A9%A1%E7%9A%AE&ie=utf-8) ，原始发布地址：https://tieba.baidu.com/p/4518179164?see_lz=1。
请大佬获得授权后更新

**Comment by ppllouf** [comment]
[汉化标题.zip](https://github.com/Xzonn/PokemonChineseTranslationRevise/files/12250094/default.zip)
精修DP的白色图标，增加Pt的开场动画白色图标

**Comment by Xzonn** [comment]
谢谢，我之后看一下。

**Comment by ppllouf** [comment]
我会继续精修一下标题图画，卧看微尘大佬已经将白金灰色图标向右飘的白色泡沫显示的问题修复。

**Comment by Xzonn** [comment]
已合并。
